//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Mitto")]
[assembly: System.Reflection.AssemblyProduct("Mitto")]
[assembly: System.Reflection.AssemblyCompany("CrazyTown Productions")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyCopyright("Copyright ©2019")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.0.1.0")]
[assembly: System.Reflection.AssemblyVersion("0.0.1.0")]


